import type { Food } from '../domain/types';

function staple(
  partial: Omit<Food, 'excluded_by_flags'> & { excluded_by_flags?: Food['excluded_by_flags'] },
): Food {
  return { excluded_by_flags: [], ...partial };
}

/**
 * Finnish grocery staples that match Linda's diet flags.
 * No dairy, bread, tofu, or land-meat items.
 * Macros are per 100 g unless noted (eggs per piece).
 */
export const SEED_FOODS: Food[] = [
  staple({
    id: 'kaurahiutaleet',
    name_fi: 'Kaurahiutaleet',
    name_en: 'Rolled oats',
    serving_unit: 'g',
    default_serving: 50,
    kcal: 370,
    protein: 13,
    carbs: 60,
    fat: 7,
    basis: 'per_100g',
    tags: ['staple', 'breakfast', 'grain'],
  }),
  staple({
    id: 'herneproteiini',
    name_fi: 'Herneproteiini',
    name_en: 'Pea protein',
    serving_unit: 'g',
    default_serving: 25,
    kcal: 380,
    protein: 80,
    carbs: 4,
    fat: 4,
    basis: 'per_100g',
    tags: ['staple', 'protein', 'powder'],
  }),
  staple({
    id: 'alpro-go-on-plain',
    name_fi: 'Alpro Go On natural',
    name_en: 'Alpro Go On plain',
    brand: 'Alpro',
    serving_unit: 'g',
    default_serving: 200,
    kcal: 60,
    protein: 5,
    carbs: 3,
    fat: 2,
    basis: 'per_100g',
    tags: ['staple', 'yogurt', 'plant'],
  }),
  staple({
    id: 'oddlygood-plain',
    name_fi: 'Oddlygood natural',
    name_en: 'Oddlygood plain',
    brand: 'Oddlygood',
    serving_unit: 'g',
    default_serving: 200,
    kcal: 60,
    protein: 5,
    carbs: 3,
    fat: 2,
    basis: 'per_100g',
    tags: ['staple', 'yogurt', 'plant', 'finnish'],
  }),
  staple({
    id: 'mustikat-pakaste',
    name_fi: 'Mustikat, pakaste',
    name_en: 'Blueberries, frozen',
    serving_unit: 'g',
    default_serving: 80,
    kcal: 57,
    protein: 0.7,
    carbs: 14,
    fat: 0.3,
    basis: 'per_100g',
    tags: ['staple', 'fruit', 'frozen'],
  }),
  staple({
    id: 'maapähkinävoi',
    name_fi: 'Maapähkinävoi',
    name_en: 'Peanut butter',
    serving_unit: 'g',
    default_serving: 12,
    kcal: 600,
    protein: 25,
    carbs: 15,
    fat: 50,
    basis: 'per_100g',
    tags: ['staple', 'fat', 'spread'],
  }),
  staple({
    id: 'muna',
    name_fi: 'Muna',
    name_en: 'Egg',
    serving_unit: 'piece',
    default_serving: 1,
    kcal: 70,
    protein: 6,
    carbs: 0.5,
    fat: 5,
    basis: 'per_piece',
    tags: ['staple', 'egg'],
  }),
  staple({
    id: 'linssit-keitetty',
    name_fi: 'Linssit, keitetty',
    name_en: 'Lentils, cooked',
    serving_unit: 'g',
    default_serving: 150,
    kcal: 115,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    basis: 'per_100g',
    tags: ['staple', 'legume'],
  }),
  staple({
    id: 'riisi-keitetty',
    name_fi: 'Riisi, keitetty',
    name_en: 'Rice, cooked',
    serving_unit: 'g',
    default_serving: 150,
    kcal: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    basis: 'per_100g',
    tags: ['staple', 'grain'],
  }),
  staple({
    id: 'pakastekasvikset',
    name_fi: 'Pakastekasvikset',
    name_en: 'Frozen mixed vegetables',
    serving_unit: 'g',
    default_serving: 200,
    kcal: 30,
    protein: 2,
    carbs: 4,
    fat: 0.2,
    basis: 'per_100g',
    tags: ['staple', 'veg', 'frozen'],
  }),
  staple({
    id: 'oliiviöljy',
    name_fi: 'Oliiviöljy',
    name_en: 'Olive oil',
    serving_unit: 'g',
    default_serving: 5,
    kcal: 900,
    protein: 0,
    carbs: 0,
    fat: 100,
    basis: 'per_100g',
    tags: ['staple', 'fat', 'oil'],
  }),
  staple({
    id: 'banaani',
    name_fi: 'Banaani',
    name_en: 'Banana',
    serving_unit: 'g',
    default_serving: 120,
    kcal: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    basis: 'per_100g',
    tags: ['staple', 'fruit'],
  }),
  staple({
    id: 'harkis-original',
    name_fi: 'Härkis Original',
    name_en: 'Härkis Original',
    brand: 'Härkis',
    serving_unit: 'g',
    default_serving: 120,
    kcal: 160,
    protein: 17,
    carbs: 6,
    fat: 6,
    basis: 'per_100g',
    tags: ['staple', 'protein', 'finnish', 'legume'],
  }),
  staple({
    id: 'beanit',
    name_fi: 'Beanit',
    name_en: 'Beanit',
    brand: 'Beanit',
    serving_unit: 'g',
    default_serving: 100,
    kcal: 160,
    protein: 17,
    carbs: 6,
    fat: 6,
    basis: 'per_100g',
    tags: ['staple', 'protein', 'finnish', 'legume'],
  }),
  staple({
    id: 'nyhtokaura',
    name_fi: 'Nyhtökaura',
    name_en: 'Pulled oats',
    brand: 'Gold&Green',
    serving_unit: 'g',
    default_serving: 100,
    kcal: 170,
    protein: 26,
    carbs: 4,
    fat: 6,
    basis: 'per_100g',
    tags: ['staple', 'protein', 'finnish', 'oat'],
  }),
  staple({
    id: 'kikherneet',
    name_fi: 'Kikherneet',
    name_en: 'Chickpeas',
    serving_unit: 'g',
    default_serving: 80,
    kcal: 160,
    protein: 9,
    carbs: 27,
    fat: 2.5,
    basis: 'per_100g',
    tags: ['staple', 'legume'],
  }),
  staple({
    id: 'kuskus',
    name_fi: 'Kuskus',
    name_en: 'Couscous',
    serving_unit: 'g',
    default_serving: 150,
    kcal: 112,
    protein: 4,
    carbs: 23,
    fat: 0.2,
    basis: 'per_100g',
    tags: ['staple', 'grain'],
  }),
  staple({
    id: 'kirjolohi',
    name_fi: 'Kirjolohi',
    name_en: 'Rainbow trout',
    serving_unit: 'g',
    default_serving: 150,
    kcal: 170,
    protein: 20,
    carbs: 0,
    fat: 10,
    basis: 'per_100g',
    tags: ['staple', 'fish', 'finnish'],
  }),
  staple({
    id: 'lohi',
    name_fi: 'Lohi',
    name_en: 'Salmon',
    serving_unit: 'g',
    default_serving: 150,
    kcal: 200,
    protein: 20,
    carbs: 0,
    fat: 13,
    basis: 'per_100g',
    tags: ['staple', 'fish'],
  }),
  staple({
    id: 'seiti',
    name_fi: 'Seiti',
    name_en: 'Saithe / pollock',
    serving_unit: 'g',
    default_serving: 150,
    kcal: 80,
    protein: 18,
    carbs: 0,
    fat: 1,
    basis: 'per_100g',
    tags: ['staple', 'fish'],
  }),
  staple({
    id: 'tonnikala-vedessa',
    name_fi: 'Tonnikala vedessä',
    name_en: 'Tuna in water',
    serving_unit: 'g',
    default_serving: 100,
    kcal: 90,
    protein: 20,
    carbs: 0,
    fat: 1,
    basis: 'per_100g',
    tags: ['staple', 'fish'],
  }),
  staple({
    id: 'soijarouhe-kuiva',
    name_fi: 'Soijarouhe, kuiva',
    name_en: 'Soy mince, dry',
    serving_unit: 'g',
    default_serving: 30,
    kcal: 330,
    protein: 50,
    carbs: 30,
    fat: 1,
    basis: 'per_100g',
    tags: ['staple', 'protein', 'soy'],
  }),
  staple({
    id: 'peruna',
    name_fi: 'Peruna',
    name_en: 'Potato',
    serving_unit: 'g',
    default_serving: 200,
    kcal: 85,
    protein: 2,
    carbs: 18,
    fat: 0.1,
    basis: 'per_100g',
    tags: ['staple', 'veg', 'finnish'],
  }),
  staple({
    id: 'omena',
    name_fi: 'Omena',
    name_en: 'Apple',
    serving_unit: 'g',
    default_serving: 100,
    kcal: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    basis: 'per_100g',
    tags: ['staple', 'fruit'],
  }),
];
